/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.tomtzook.gcmake;

import org.gradle.api.Project;
import org.gradle.api.Plugin;


public class GradleCmakePlugin implements Plugin<Project> {

    public void apply(Project project) {
        
    }
}
